### ISSUE TITLE
Filter out allies and supporters

### ISSUE THREAD

**Issue by sebastianruder** [ojahnn/acl2020-urm-papers#1]
The BIG directory also contains allies and supporters, which are currently included in the list of papers (e.g. two papers by me are included even though none of my co-authors are members of under-represented groups). An potential imperfect workaround would be to filter authors where the free text in the BIG directory includes certain keywords such as "support", "ally". Looking at the list, this would also include many false positives, however. :-/

**Comment by eseyffarth** [comment]
Isabelle Augenstein has changed the downloadable CSV of the BIG Directory so as to include either only members, or only supporters. The current version in this repo is the version including members.
